openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-96mg.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        description: User registration information
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                name:
                  type: string
              required:
                - email
                - password
                - name
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                        format: email
        '409':
          description: Email already in use

  /auth/login:
    post:
      summary: Log in a user
      requestBody:
        description: User login credentials
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: User successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      accessToken:
                        type: string
        '401':
          description: Invalid email or password
        '404':
          description: Email not found

  /auth/refresh:
    post:
      summary: Refresh authentication session
      responses:
        '200':
          description: Session successfully refreshed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      accessToken:
                        type: string
        '401':
          description: Session or refresh token missing or expired

  /auth/logout:
    post:
      summary: Log out a user
      responses:
        '204':
          description: User successfully logged out
        '401':
          description: Session not found

  /auth/request-reset-email:
    post:
      summary: Request password reset email
      requestBody:
        description: Email for password reset
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
              required:
                - email
      responses:
        '200':
          description: Password reset email sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
        '400':
          description: Email is required

  /auth/reset-password:
    post:
      summary: Reset user password
      requestBody:
        description: Reset password information
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                password:
                  type: string
              required:
                - token
                - password
      responses:
        '200':
          description: Password successfully reset
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
        '400':
          description: Token and new password are required


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
